name: Create Release from Tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Extract Version from Tag
        id: get_version
        run: |
          # GITHUB_REF to np. refs/tags/v1.2.3
          TAG_NAME=${GITHUB_REF#refs/tags/}
          # Usuwamy literkę 'v' jeśli jest na początku, żeby do Mavena trafiło czyste 1.2.3
          VERSION=${TAG_NAME#v}
          
          echo "Detected version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Set Maven Version
        run: mvn versions:set -DnewVersion=${{ steps.get_version.outputs.version }}

      - name: Build with Maven
        run: |
          mvn versions:set -DnewVersion=${{ steps.get_version.outputs.version }} -DgenerateBackupPoms=false
          mvn clean package

      - name: Create ZIP Package
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          ZIP_NAME=TreeCmp-$VERSION.zip
          
          mkdir -p dist/config          
          cp target/TreeCmp-$VERSION.jar dist/
          cp config/config.xml dist/config/
          cd dist
          zip -r ../$ZIP_NAME .
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.tag_name }}
          tag_name: ${{ steps.get_version.outputs.tag_name }}
          files: TreeCmp-${{ steps.get_version.outputs.version }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}